tests: Fix meson setup with pygobject >= 3.52.0
With pygobject >= 3.52.0, importing GIRepository-2.0 is no longer
supported.  So if both pygobject >= 3.52.0 and python-dbusmock are
installed, meson setup will error out:

    ../tests/meson.build:22:6: ERROR: Command `<PKGDIR>/gnome-bluetooth-47.1/tests/unittest_inspector.py <PKGDIR>/gnome-bluetooth-47.1/tests/integration-test.py` failed with status 1.

And running tests/unittest_inspector.py gives:

    Traceback (most recent call last):
      File "<PKGDIR>/tests/integration-test.py", line 35, in <module>
        gi.require_version('GIRepository', '2.0')
        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.13/site-packages/gi/__init__.py", line 132, in require_version
        raise ValueError('Namespace %s not available for version %s' %
                         (namespace, version))
    ValueError: Namespace GIRepository not available for version 2.0

even though GIRepository-2.0.typelib is installed on the system.

Instead of complicating the test code with conditionalizing between
GIRepository-2.0 and GIRepository-3.0, we can drop the dependency on
GIRepository and rely on GIRepository's own envvar GI_TYPELIB_PATH to
help it find our freshly built typelib.

Reported-by: Wayne Blaszczyk <wblaszcz@bigpond.net.au>
Closes: https://lists.linuxfromscratch.org/sympa/arc/blfs-support/2025-03/msg00112.html